### ISSUE TITLE
dead keys, from international keyboard layout, don't work in terminal

### ISSUE THREAD

**Issue by goretkin** [jupyter/tmpnb#111]
I am not sure if this is the correct place to post this issue, sorry.

The terminal in tmpnb.org doesn't behave well with "dead keys". I am using the "U.S. International - PC" keyboard layout in mac os x and both in Safari and Firefox I cannot type in a quote `"` or tilde `~` characters, and etc.  

As far as I understand dead key works as follows: 
To type `ä` you would press `"` and then `a`. To type `"` you would press `"` and `space`. Alternatively, if you're following the `"` character with a non-diacritic-able character, you could just type that character. For example, I don't think h-with-trema exists, so you could get the string `"h` by typing `"` and `h` (you could also put a `space` between those two keystrokes for the same effect)

There are a few different ways I've seen applications handle deadkeys.
1. When you press a dead key, nothing happens. A character gets emitted if you do one of the three things above (a. hit space, b. hit a diacritic-able character, c. hit a non-diacritic-able character)
2. When you press a dead key, the character appears as if it weren't a dead key. It then a. stays there and cursor moves over, b. gets replaced by, e.g. `ä`, c. stays there, another character gets emitted, and the cursor moves over two spaces`

Some applications that do number 2 will highlight the character or underline the character immediately after hitting a dead key to indicate that it is not totally emitted yet. Note that the notebook cell does number 2, without any of the indications I just mentioned.

**Comment by rgbkrk** [comment]
Closing in favor of current issues reported on ipython/ipython and on jupyter/notebook.
