### ISSUE TITLE
Provide ability to modify headers

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/tmpnb#115]
As is done in https://github.com/odewahn/tmpnb/commit/3edc90a5e741144d95ba4325ec8e425e9f4c5a72, we should provide configurability of the headers on all endpoints we can touch.

**Comment by captainsafia** [comment]
Let me see what I can do with this. I was thinking of adding the configurability to the `BaseHandler` introduced in #151. 

Are there specific header fields that have a higher priority for implementation?

**Comment by rgbkrk** [comment]
Mostly CORS headers, though we could do it in a traitlets like way -- the same way that the jupyter [notebook does by using `tornado_settings`](https://github.com/jupyter/docker-demo-images/blob/master/common/profile_default/ipython_notebook_config.py#L21-L26):

```
c.NotebookApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'self' https://*.jupyter.org https://jupyter.github.io https://*.tmpnb.org"
    },
    'static_url_prefix': 'https://cdn.jupyter.org/notebook/try/'
}
```

We've been doing allow origin in a separate way / in addition too.

**Comment by captainsafia** [comment]
Hm. OK. I'm gonna have a stab at this with traitlets for consistency across the ecosystem.

**Comment by captainsafia** [comment]
@rgbkrk — gonna go ahead and implement this one using `tornado.options`. I'll open up another issue for migrating everything to use traitlets since that appears to be a process in and off itself.
