### ISSUE TITLE
Provide architecture diagrams

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/tmpnb#119]
To kick things off, here's one I mocked up tonight:

![tmpnb](https://cloud.githubusercontent.com/assets/836375/5849193/929f4c2a-a1a7-11e4-8e76-fd5ce09f6b8e.png)

**Comment by rgbkrk** [comment]
Weird. The fonts changed on me.

**Comment by rgbkrk** [comment]
![tmpnb 1](https://cloud.githubusercontent.com/assets/836375/5849202/e40fddcc-a1a7-11e4-9917-37887f1b4bdb.png)

**Comment by rgbkrk** [comment]
![tmpnb 2](https://cloud.githubusercontent.com/assets/836375/5849242/7349ac8e-a1a8-11e4-981b-8b7741b00037.png)

**Comment by rgbkrk** [comment]
Now with fixed fonts! 

![tmpnb 4](https://cloud.githubusercontent.com/assets/836375/5909206/f0b156da-a573-11e4-8e3f-f65dfe9d23b8.png)

**Comment by minrk** [comment]
Does it make sense that the arrows for CHP:user container are in the opposite direction to CHP:orchestrate?

**Comment by rgbkrk** [comment]
> Does it make sense that the arrows for CHP:user container are in the opposite direction to CHP:orchestrate?

They sure don't, especially when matched up with how the arrows with the proxy and orchestration are drawn. I'll fix that.

What do you think about the user arrow? That should be pointing to the proxy too huh?

**Comment by rgbkrk** [comment]
![tmpnb architecture](https://cloud.githubusercontent.com/assets/836375/5911140/c53e3978-a587-11e4-86a5-695469ef23a5.png)

**Comment by rgbkrk** [comment]
Well @minrk, here's a quick little tmpnb redirector ![tmpnb-redirector](https://cloud.githubusercontent.com/assets/836375/5913707/3b282e20-a5ae-11e4-9768-c22089b70497.png)

**Comment by minrk** [comment]
HyperTextTmpnbTransferProtocol?

Otherwise, looks good.

**Comment by rgbkrk** [comment]
> HyperTextTmpnbTransferProtocol?

Ha!
