### ISSUE TITLE
Python urllib2 bug

### ISSUE THREAD

**Issue by keeganhines** [jupyter/tmpnb#120]
Hey @rgbkrk, just some strange behavior I noticed. The Python2 kernels have urllib2 installed, but calling out to get web data from this library results in an error.

```
import urllib2
urllib2.urlopen('http://www.example.com').read()
```

 Perhaps this is due to a server configuration and how the notebooks are hosted, but I wanted to bring it your attention.

**Comment by Carreau** [comment]
Containers are by design isolated from any network access to avoid mining bitcoin, DDOS smth, span...
So what you are seeing is probably that. We are considering whitelisting a few domains though.

**Comment by rgbkrk** [comment]
Thanks for reporting @keeganhines. 

This definitely reminds me that I need to link to all the related repositories in the README and example notebooks:

* [jupyter/tmpnb-deploy](https://github.com/jupyter/tmpnb-deploy) - [locks down networking for Docker](https://github.com/jupyter/tmpnb-deploy/blob/51d4cdcdd46d887f4af04017bcf7d8bc4444bde2/roles/notebook/files/docker#L3)
* [jupyter/docker-demo-images](https://github.com/jupyter/docker-demo-images)

We'll need attributable users before I'm willing to have network access. We didn't detect issues, but I wanted to lower the risks while still providing a resource/sandbox/proving ground.
