### ISSUE TITLE
idea/feature - real time collaborative coding

### ISSUE THREAD

**Issue by nymoorland** [jupyter/tmpnb#139]
Well, it's not really an issue. It would be cool if github had idea/cool feature ideas bucket. Anyway, I was screensharing some code with someone with whom I am working. I remembered the R kernel and thought it would be neat to do some real-time collaborative coding. There are some web editors where you share a link and code together. Is this already available? I am not familiar with the architecture of the service but it would be great for educational purpose and collaboration. Just throwing it out there.

Also, what is the difference between tmpnb and try.jupyter. Is tmpnb deprecated?

**Comment by rgbkrk** [comment]
The realtime collaborative features of the notebook are ongoing, mostly motivated in https://github.com/jupyter/jupyter-drive.

tmpnb.org and try.jupyter.org are actually both running on top of tmpnb.org. https://github.com/jupyter/try.jupyter.org is really just an single static HTML page with an iframe containing tmpnb.org. As far as the tech is concerned, tmpnb (this repo), is our current instant, anonymous, ephemeral setup.

**Comment by nymoorland** [comment]
Yes, I can read that info in your docs. Please add it to the wishlist either here or in the relevant repo. Thanks. @takluyver @minrk

**Comment by rgbkrk** [comment]
Which piece for the wishlist? Realtime collaboration?

**Comment by rgbkrk** [comment]
This type of feature has to be enabled in the underlying container and is certainly on the radar of @Carreau both in issues and in the current roadmap.

Closing since not part of tmpnb.
