### ISSUE TITLE
Port codebase to use traitlets

### ISSUE THREAD

**Issue by captainsafia** [jupyter/tmpnb#160]
Use `traitlets` instead of `tornado.options`!

**Comment by minrk** [comment]
I'm not actually sure we should, but it might become helpful if the configuration continues to get more complex. @rgbkrk what do you think?

**Comment by rgbkrk** [comment]
The main reason I suggested traitlets was so that specifying the JSON format for the tornado headers was simple and similar to the Jupyter notebook config.

**Comment by minrk** [comment]
ok, if there's something that's actually simpler, then go for it. I just don't want to be pushing traitlets on every entrypoint, since it's frequently overkill.

**Comment by rgbkrk** [comment]
I think @captainsafia's PR for #161 addresses what we really needed in CORS headers, though I'd also like to be able to specify other headers via `tornado_settings`.

**Comment by rgbkrk** [comment]
Closing for now, since we have what we need and there's API design to go after soon (in tandem with binder).

**Comment by captainsafia** [comment]
Closed.
