### ISSUE TITLE
Option to launch containers with --net=host for Spark compatibility

### ISSUE THREAD

**Issue by parente** [jupyter/tmpnb#169]
This might be a highly specialized use case, but I figured I'd file it and see where it goes. I will implement it and keep it in a fork if it doesn't make sense upstream here.

If I want to launch Jupyter Notebook containers that talk to a Spark cluster (not just Spark local mode), the workers on that cluster need to be able to talk back to the launched containers. tmpnb currently configures containers with networking bridged through the docker0 interface (the docker default). When Spark workers try to "phone home" to the Spark driver running in one of these containers:

1. It has the wrong IP address: the Spark driver communicates its internal Docker IP
2. Even if it had the right IP, the ports randomly selected by the driver to listen for worker connections are not exposed.

The simplest fix we've found is to launch containers with `--net=host`, do a bit of port management to ensure there's no conflicts, and ensure that appropriate host firewall rules are set to disallow connections to those containers except by a local proxy and other workers in the cluster. To allow tmpnb to support this mode of operation, I image:

- A command line switch to configure orchestrate.py to launch containers with --net=host
- Lots of doc on that switch stating the implications of running that way :)
- Change in the code path from orchestrate down to the spawner to pass that option
- New logic in the spawner to allocate non-overlapping host ports to containers

**Comment by rgbkrk** [comment]
I'm assuming that linking doesn't solve this problem either?

> Lots of doc on that switch stating the implications of running that way :)

Most certainly.

**Comment by parente** [comment]
To the best of my knowledge, linking doesn't help because the Spark workers are on altogether separate hosts from the container->notebook->kernel->Spark-drivers.

**Comment by parente** [comment]
This was merged.
