### ISSUE TITLE
R, Julia examples not working

### ISSUE THREAD

**Issue by episodeyang** [jupyter/tmpnb#176]
Hi,

My friend in statistics wants to try out jupyter for R. I recommended the try.jupyter.org to him for starters, but it looks like the R example is not working. 

I also checked and it seems that the plotting in Julia is also not working. I have already contacted the iRkernel contributors [here](https://github.com/IRkernel/IRkernel/issues/192), but any help from folks here would be greatly appreciated!

Best,
Ge

**Comment by captainsafia** [comment]
You are correct. I noticed this problem a while ago too but never had the foresight to make an issue for it (thanks for that!)

I'll look into it and hopefully have something to report this weekend.

**Comment by episodeyang** [comment]
Hi @captainsafia it seems it is fixed for now from the issues, but I haven't checked with production.

Thanks for the response!

**Comment by captainsafia** [comment]
Both the R and Julia kernels work in production so I am going to go ahead and close this issue.
