### ISSUE TITLE
Update default command to call start-notebook.sh

### ISSUE THREAD

**Issue by DavidPowell** [jupyter/tmpnb#180]
All the recent jupyter docker images have a default command `start-notebook.sh`. The main function of this command appears to be to launch the notebook as the user jovyan, rather than as root.

However, orchestrate.py defaults to running `ipython notebook`, which (aside from being out of date) bypasses this command, and leaves the notebook server running as root. Although running as root inside a docker container is not as serious as on the host, it's definitely not best-practice security.

Attempting to pass `start-notebook.sh` as the `--command` option to `orchestrate.py` causes an error with `su` not recognising the `--ip=0.0.0.0` option. I presume this means that something is being escaped incorrectly, but I'm not sure what.

I think the ideal solution would be that `start-notebook.sh` is called by default, but in the mean-time I'd welcome a temporary solution so I can override this manually.

**Comment by parente** [comment]
The playbook for the tmpnb.org site sets the command like so:

https://github.com/jupyter/tmpnb-deploy/blob/master/vars.yml#L10

**Comment by rgbkrk** [comment]
We should definitely change our docs to reflect the current startup setup, possibly the defaults too.

**Comment by rgbkrk** [comment]
In fact, the default command rendered by tmpnb should either be that shell script with args or jupyter notebook.
