### ISSUE TITLE
Logging usage statistics

### ISSUE THREAD

**Issue by elliottslaughter** [jupyter/tmpnb#192]
Is there any way to ask tmpnb to log usage statistics? E.g.

  * Number of users over a certain period of time
  * Maximum concurrent users over a certain period
  * Number of users the "not enough instances" page

I could probably capture some of this via a standard web analytics package, assuming I can figure out where to stuff the code (can I override `templates/ga.html`?). But for certain quantities of interest that will at best be an approximation; e.g. the number of allocated/remaining instances are a function of how frequently tmpnb checks for idleness, etc., and are only really known to the server.

**Comment by captainsafia** [comment]
I'm not sure if this satisfies your needs, but the `/api/stats/` endpoint should satisfy your needs. It provides basic information about the number of available and allocated containers at a certain point in time. You can create a then wrapper around this endpoint that queries it at a certain interval and stores the resulting information.

The API won't provide the number of users who are not allocated to an instance, though.

**Comment by elliottslaughter** [comment]
That should do nicely, thanks.
