### ISSUE TITLE
Page to show on resource exhaustion

### ISSUE THREAD

**Issue by elliottslaughter** [jupyter/tmpnb#194]
Currently, when a user shows up and there isn't a container available, tmpnb shows the "No Vacancy" page and waits to refresh to see if something will become available. This is nice, but if the system is really oversubscribed (e.g. you get an unexpected spike in traffic), it might be nice to show e.g. a static rendered version of the notebook instead, either via a link or a redirect.

(Of course you still have to think of this in advance, but let's suppose that you have, and that you're willing to render the notebook to static HTML yourself.)

Is there any way to customize the response tmpnb shows to the user when resources are exhausted?

**Comment by captainsafia** [comment]
Yes, this is possible. You can implement a redirector in the except clause on the `SpawnHandler` to a static version of the Notebook on nbviewer. You will need to edit [these lines of code](https://github.com/jupyter/tmpnb/blob/master/orchestrate.py#L142).

Let me know if you have more questions.

**Comment by elliottslaughter** [comment]
Thanks for the pointers; I've got a working solution now.
