### ISSUE TITLE
quickstart works like a charm, stackimage examples fail though

### ISSUE THREAD

**Issue by knaani** [jupyter/tmpnb#211]
love your project, got the quick start example to work as stated (on OS X /server). When trying to go beyond to use docker-stacks images, the command simply processed, yielding a string beginning with the tmpnb container-id, however tmpnb or containers spawning the notebooks never showed up in docker ps OR docker ps -a. Where am I going wrong? Thanks! K

**Comment by parente** [comment]
I noticed there's at least one typo in the README regarding the docker-stacks images. Can you try this command and let me know if it works for you? If it does, we'll update the README.

```
docker run -d \
	--net=host \
	-e CONFIGPROXY_AUTH_TOKEN=$TOKEN \
	-v /var/run/docker.sock:/docker.sock \
	jupyter/tmpnb \
	python orchestrate.py --image='jupyter/minimal-notebook' \
		--pool_size=4 \
		--command='start-notebook.sh \
			"--NotebookApp.base_url={base_path} \
			--ip=0.0.0.0 \
			--port={port} \
			--NotebookApp.trust_xheaders=True"'
```

**Comment by knaani** [comment]
thanks very much!! - it works indeed. Also w/other images :)
Whatta great application.

**Comment by parente** [comment]
I'll keep this one open to update the example in the README. Glad it worked for you.
