### ISSUE TITLE
Adding additional kernels (e.g. for C++, Ruby, Java etc. ) to tmpnb 

### ISSUE THREAD

**Issue by rtwk** [jupyter/tmpnb#212]
I have managed to successfully run tmpnb on a local Ubuntu server and can access it via browser. Jupyter supports so many programming languages. How to add kernels for those languages on top of tmpnb. Any reference or guide will be greatly appreciated.

**Comment by rtwk** [comment]
Well, looking into the https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile, it seems that one needs to create a dockerfile including kernels desired, then build image and run it using docker run using tmpnb. Am I missing something?

**Comment by rgbkrk** [comment]
>  it seems that one needs to create a dockerfile including kernels desired, then build image and run it using docker run using tmpnb

That's correct. You may find what you want within [docker-stacks](https://github.com/jupyter/docker-stacks)

**Comment by parente** [comment]
> , it seems that one needs to create a dockerfile including kernels desired, then build image and run it using docker run using tmpnb. Am I missing something?

I've also got the equivalent really-dumb-but-easy-to-read make-based automation equivalent of https://github.com/jupyter/docker-stacks/tree/master/examples/make-deploy for tmpnb sitting around on my hard drive somewhere. Would it help if that got contributed here?

**Comment by rgbkrk** [comment]
Definitely welcome!
