### ISSUE TITLE
Error while building try.tmpnb docker image from given dockerfile

### ISSUE THREAD

**Issue by rtwk** [jupyter/tmpnb#215]
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies nmatrix (= 0.2.0) and nmatrix (~> 0.1)
  Activated nmatrix-0.1.0 via:
    nmatrix-0.1.0 (~> 0.1), sciruby-full-0.2.8 (= 0.2.8)
  instead of (= 0.2.0) via:
    nmatrix-lapacke-0.2.0 (~> 0.2.0), mixed_models-0.1.1 (~> 0.1), sciruby-full-0.2.8 (= 0.2.8)
The command '/bin/sh -c gem install --no-rdoc --no-ri sciruby-full' returned a non-zero code: 1

**Comment by parente** [comment]
Yes. sci-ruby has a build bug at the moment. The jupyter/demo rebuild issue caused by it is being tracked in jupyter/docker-demo-images#83.

**Comment by rtwk** [comment]
Okay, it seems that commenting out the sciruby install line will be able to successfully build the image. Closing the issue.
