### ISSUE TITLE
auto-executing python startup scripts when initialising kernels

### ISSUE THREAD

**Issue by knaani** [jupyter/tmpnb#216]
hello! - I am trying to get a python script to execute automatically whenever a user runs a new python kernel from a jupyter instance spawned via tmpnb. - What would be the right way to do this? Too since the script would vary, it would be a pain having to create custom docker images for each use-case.
Sorry if I am just missing the obvious & thanks for any suggestions.
k.

**Comment by minrk** [comment]
How would the script vary?

**Comment by minrk** [comment]
(based on what input, that is)

**Comment by rgbkrk** [comment]
tmpnb allows you to start up a docker container for a user that can have any amount of config baked in. Which means that you only get configurability at the level of which Docker container you run. No parameters are accepted, one of the biggest reasons of which is caching.

**Comment by knaani** [comment]
... thanks for looking into this - so in principle, if some sets of analytics applying to distinct use cases are to be floated to a site audience, a container should be defined for each case (that is if I have a preference for not forking the applications within the notebook app)?
In essence any of those scripts would work with scipy-notebook from docker-stacks, just adding a few additional py libraries. So one would have to draft use-case based dockerfiles based on scipy-notebook. I guess to me it just looked somewhat disproportionate given the notebook initialisation script being the only distinction;)

**Comment by rgbkrk** [comment]
Yeah, and an easier mode might be for you to use [mybinder](http://mybinder.org/) to build the docker images for you based on a repository.

**Comment by knaani** [comment]
...thanks I will try to work ssh out.
Meanwhile... I was just thinking of a more generic approach: ipython looks up and runs files located in the $USER/startup directory when launching a nb, so jovyan/startup in the case of jupyter I guess. So if there is a way to simply mount some host directory (which I'd call startup) in the user folder of the jupyter containers being spawned by tmpnb, that would actually resolve the issue too. (How) could that work?

**Comment by minrk** [comment]
@knaani it's still IPython, so the same .ipython/profile_default/startup directory will be used in notebooks.

**Comment by knaani** [comment]
...here goes some belated thanks for your support ;) 
I did have to play around a bit to find out whichever way would give me maximum flexibility and here's what worxx for me:

1) I created my own python class library covering the use-cases I needed
2) ...included it using a Dockerfile based on jupyter/minimal-notebook (like the scipy one) as:
...
USER root
COPY mylib mylib
WORKDIR mylib
RUN $CONDA_DIR/envs/python2/bin/python setup.py install
WORKDIR ..
RUN rm -rf mylib
USER jovyan
...
where mylib is a folder setup as a regular python library package.

and 3) placed a py startup script in the mentioned profile startup directory pre-loading the classes to have them immediately available (also as USER root in the Dockerfile):
...
COPY 001.py /home/jovyan/.ipython/profile_default/startup/001.py
RUN chown -R jovyan:users /home/jovyan/.ipython
...
So I think this can be closed ;)
Cheers, k
