### ISSUE TITLE
nonstandard public facing (proxy) port does not seem to work

### ISSUE THREAD

**Issue by oroszl** [jupyter/tmpnb#224]
Hi Guys!
I would like to add a tmpnb like service to one of our projects and I hit on a seemingly puzzleing issue.
It seems if I change the public facing port of the proxy that is put in front of tmpnb than my I can not get through the dashboard.
The following seems to reproduce the problem on a clean instance of a docker-machine created virtualbox instance. 

```bash
export TOKEN=$( head -c 30 /dev/urandom | xxd -p )
docker run --net=host \
           -d \
           -e CONFIGPROXY_AUTH_TOKEN=$TOKEN \
           --name=proxy \
           jupyter/configurable-http-proxy \
           --default-target http://127.0.0.1:9999 \
           --port=8008 # THIS IS THE ONLY EXTRA THING I ADDED 

docker run --net=host \ 
                   -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN \
                   --name=tmpnb \
                   -v /var/run/docker.sock:/docker.sock \
                   jupyter/tmpnb
```
If I go now to port 8008 of my virtualmachine I get to the following screen:
![image](https://cloud.githubusercontent.com/assets/1990999/13550364/491a1da2-e31c-11e5-855d-ad055ab2fb5b.png)

`docker ps -a` on the virtualmachine gives 
![image](https://cloud.githubusercontent.com/assets/1990999/13550387/e841e84c-e31c-11e5-8c4f-c4f66cf5ce93.png)
that is, it seems that tmpnb provisioned all the containers the proxy is live and well.

If on the other hand I omit the `--port=8008` flag and visit port 8000 of the virtual machine I get this (as expected)
![image](https://cloud.githubusercontent.com/assets/1990999/13550432/d6c87260-e31d-11e5-8eca-9a0ff3f16edf.png)

- am I missing something ?
- does tmpnb need to be informed about the public facing port of the proxy ?
- is the `--port` flag not what I think it is ?

**Comment by parente** [comment]
If you set `--port` on the configurable-http-proxy, it sets the API port to that port number + 1 unless you also set `--api-port`. See https://github.com/jupyter/configurable-http-proxy/blob/201a6033309e2a9a2106fbd5f73217c72df8ff9f/bin/configurable-http-proxy#L177.

In either case, you need to tell the tmpnb server where that proxy endpoint is by setting environment variable `CONFIGPROXY_ENDPOINT`. See https://github.com/jupyter/tmpnb/blob/d974546f90b6811d462fe494e2d119ffccdce633/orchestrate.py#L333.

So in your case above `-e CONFIGPROXY_ENDPOINT=http://127.0.0.1:8081` should do the trick.

And yes. All of this should be documented somewhere. :eyes:

**Comment by oroszl** [comment]
Thanks !
So manually adding the flags `--port=8008` `--api-port=8001` at proxy startup also does the trick. 
Where do I need to raise the issue so that this can appear in the appropriate documentation  ?
It would be nice if this could be burned in to the proxy help string.
Anyway, thanks for the help, I think we can close the issue here.

**Comment by parente** [comment]
We can leave this one open and file the doc fix against it. I think a hint here in the README to the effect of what I said or what you did is one part. A PR against jupyter/configurable-http-proxy to document the port+1 behavior is probably also in order.

**Comment by rgbkrk** [comment]
Thanks @parente for the doc fix and @oroszl for the issue report!
