### ISSUE TITLE
Start with specific notebook, skip browser

### ISSUE THREAD

**Issue by tammojan** [jupyter/tmpnb#225]
I'm writing a tutorial + kernel for my favorite language, TaQL. I'd like to redirect tmpnb directly to the notebook, instead of presenting users with the Jupyter browser first (so exactly the Nature use case). Where would I specify this? Since jupyter launches with `--no-browser`, I cannot specify it as a command line option to `jupyer`. I'm using `start-notebook.sh`, etc.

If this is the wrong place to ask this, please point to a better place. Thanks!

**Comment by rgbkrk** [comment]
As long as the notebook will always be in the same place, there's a `--redirect-uri` option to tmpnb (`orchestrate.py`).

```
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN \
           -v /var/run/docker.sock:/docker.sock \
           jupyter/tmpnb python orchestrate.py \
             --image='jupyter/nature-demo' \
             --redirect-uri='/notebooks/Nature.ipynb' \
             --command="jupyter notebook --NotebookApp.base_url={base_path} --ip=0.0.0.0 --port {port}"
```

I can't recall if/how our command differs there.

**Comment by tammojan** [comment]
@rgbkrk Great, that works. Thanks for the quick reply!

**Comment by rgbkrk** [comment]
No problem. :cake:
