### ISSUE TITLE
using host_directories option for a user defined mount point

### ISSUE THREAD

**Issue by apurva3000** [jupyter/tmpnb#226]
Is there any workaround to use the host_directories option for mounting host directories to a user defined mount point in the container,  when launching with orchestrate.py ?
For example, currently if you try to specify a directory with host_directories='/path/to/:rw' it would mount it in /mnt/vol0 or something like that, It would be nice to have a user defined mount location.

**Comment by parente** [comment]
Looks like no today:

https://github.com/jupyter/tmpnb/pull/197/files#diff-8a14bdd394a2783916dda2a491849dabR122

Shouldn't be too hard to extend that logic to support the full docker syntax of `<host_dir>[:container_dir][:permissions]` as long as the underlying dockerpy lib allows it.

**Comment by apurva3000** [comment]
Thanks.
It should be like the docker style IMO, eg. "/path/to:/usermount/path/:ro,"other/path/:/usermount/otherpath/:ro"

**Comment by SergeyParamoshkin** [comment]
--host-directories=/tmp/data:/home/jovyan/work:rw

**Comment by lokinell** [comment]
I cannot see my created notebook file in the host_directories by setting --host-directories.
The /tmp/data directory will be created in the host, but notebook files will not save in this directory.

**Comment by reaganch** [comment]
I've been trying to host a tmpnb server on my computer to allow students from my class to access a set of jupyter notebooks. I've been able to successfully host a tmpnb server using the following commands

    docker pull jupyter/minimal-notebook
    export TOKEN=$( head -c 30 /dev/urandom | xxd -p )
    docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999
    docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=tmpnb -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --container-user=jovyan --command='jupyter notebook --no-browser --port {port} --ip=0.0.0.0 --NotebookApp.base_url=/{base_path} --NotebookApp.port_retries=0 --NotebookApp.token="" --NotebookApp.disable_check_xsrf=True'

This launches a jupyter/minimal-notebook container each time I visit localhost:8000. I, however, cannot seem to figure out how to copy the *.ipynb files from a directory on my computer into the /home/jovyan/work directory each time a container is launched. I'm assuming the --host-directories command is the thing I need to use, but would be helpful if someone can fill me up on whether I'm missing something here.

**Comment by reaganch** [comment]
Never mind. Just saw #264 that discusses just this. Would be great if this feature to specify the mount point as /home/jovyan/work could be implemented in this main jupyter/tmpnb repo.

**Comment by jeremysalwen** [comment]
@apurva3000 Can you make this into a pull request?  Your patch looks great and it would be nice if this was part of master.

**Comment by apurva3000** [comment]
@jeremysalwen  For some reason, my email puts all the github mentions in "forum" section which are lost with other mails. I will create a pull request right away. I was cleaning up my inbox and found your message.
