### ISSUE TITLE
running example gives error 500

### ISSUE THREAD

**Issue by gijzelaerr** [jupyter/tmpnb#228]
Hi!

I try to run your example, but it doesn't work for me. 

I run it like this ( i need to set the port for firewall):
```
docker pull jupyter/minimal-notebook
export TOKEN=$( head -c 30 /dev/urandom | xxd -p )
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999 --port 8080
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=tmpnb -v /var/run/docker.sock:/docker.sock jupyter/tmpnb
```

When tmpnb then tries to start a notebook I get a 500 http error page.

the tmpnb logs look like this:

https://gist.github.com/gijzelaerr/490f40cc404dbdfb23b5

I've removed *all* containers, also stopped. I also removed all images, except the required ones.

i'm using the latest docker:
```
$ docker --version
Docker version 1.10.3, build 20f81dd
```

**Comment by parente** [comment]
If you change the proxy port, its internal port also changes to that port+1 unless you specify it otherwise.

https://github.com/jupyter/tmpnb/issues/224 had a comment about updating the README here with this information. It got closed without the update.

**Comment by gijzelaerr** [comment]
thanks!

**Comment by jermwatt** [comment]
How do you specify the internal port number  /  proxy port number?  In other words, what does this 

If you change the proxy port, its internal port also changes to that port+1 unless you specify it otherwise.

mean?
