### ISSUE TITLE
set CPU quota

### ISSUE THREAD

**Issue by minrk** [jupyter/tmpnb#239]
We are currently using CPU shares, which allows a single instance to take up 100% of available CPU, as long as nobody else is around. We should probably also set a CPU quota, so we can limit the resources used by a single container, even if they are all alone.

**Comment by captainsafia** [comment]
Did this have anything to do with the recent outage by any chance?

Also, thanks for taking care of it! 💃

**Comment by minrk** [comment]
I think it is, but there could also be some factors related to how we are deploying it that we're working on separately.
