### ISSUE TITLE
Is tmpnb down?

### ISSUE THREAD

**Issue by charnpreetsingh185** [jupyter/tmpnb#246]
I am trying to access tmpnb.org through "Try Jupyter" from the main website and it seems to be down.

Attached screen shot of ping results.

![screen shot 2016-07-07 at 4 37 58 pm](https://cloud.githubusercontent.com/assets/16314651/16673274/97d343fa-4461-11e6-8fae-a4e7f7892756.png)

**Comment by minrk** [comment]
Yes, tmpnb appears to be down. cc @rgbkrk

**Comment by carolynvs** [comment]
Our account slipped through the cracks when Kyle handed it off to me. I am working with Rackspace to get it reinstated.

**Comment by willingc** [comment]
Thanks @carolynvs. How to Whale is looking good too ;-)

**Comment by minrk** [comment]
Thanks, @carolynvs! I put up a temporary clone of tmpnb at tmpnb.jupyter.org and pointed try.jupyter.org to it in the meantime.

**Comment by willingc** [comment]
Thanks @minrk.

**Comment by carolynvs** [comment]
@minrk The account has been reinstated. Let me know if there's anything else I can do to help.

**Comment by minrk** [comment]
Thanks @carolynvs everything appears to be back in working order.
