### ISSUE TITLE
Respond to OPTIONS request

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/tmpnb#247]
We need to respond to OPTIONS requests with the CORS headers we care about. This was done in the main notebook.

```
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:3000' is therefore not allowed access. The response had HTTP status code 405.
```
- [ ] implement in tmpnb
- [ ] implement in tmpnb-redirector

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by SylvainCorlay** [comment]
Do we only need to set the default value of 'Access-Control-Allow-Methods' to `GET, PUT, POST, PATCH, DELETE, OPTIONS'` ?

**Comment by rgbkrk** [comment]
I think so.
