### ISSUE TITLE
token authentication

### ISSUE THREAD

**Issue by izahn** [jupyter/tmpnb#256]
Since Notebook 4.3 token authentication is on by default, and my tmpnb installation started asking for password. I eventually figured out I could set `--NotebookApp.token=""`, but I'm not sure if that is safe or if there is a recommended way. (I guess it is as safe as it was before since token authentication was disabled by default before. Or do I have that wrong?). 

I saw https://github.com/jupyter/tmpnb/issues/255 which seems related. Should I be using https://github.com/yuvipanda/jupyterhub-tmpauthenticator?

**Comment by rgbkrk** [comment]
That's correct, you now need to set the `token` to `''` for tmpnb installations.

**Comment by minrk** [comment]
I'm working on an update to tmpnb that will use the tokens to login users when they get their containers, making it a nice security improvement for tmpnb.
