### ISSUE TITLE
Add Readme.md security warning

### ISSUE THREAD

**Issue by misolietavec** [jupyter/tmpnb#266]
I discovered the minergate-cli (cryptocurrency miner) running in one of tmpnb containers, fully eating all the 16 cores on server. There should be a strong warning in "Quick start" session of Readme.md that it is possible to install and run arbitrary softvare as root in the container with that simple configuration. It is very dangerous, especially if running containers several days...

**Comment by misolietavec** [comment]
Hmm, the warning itself is not helpful. Notebooks in containers will start as root (can I start the `docker run ...` as ordinary user?). This can be cured by adding the option `--container-user=jovyan` to  orchestrate.py in the sample command in section "Quick start". May I suggest to add this to Readme.md? I think, this can help many users.

**Comment by rgbkrk** [comment]
Sure, feel free to make a PR.

**Comment by misolietavec** [comment]
PR made, merged. I can close the issue.

**Comment by willingc** [comment]
Thanks @misolietavec!
