### ISSUE TITLE
Image in docker registry not up-to date

### ISSUE THREAD

**Issue by misolietavec** [jupyter/tmpnb#269]
docker pull jupyter/tmpnb gives the image with python 2.7, probably from base image 
python:2.7-wheezy. Dockerfile in this repository states python:3.4-wheezy as base image (as of febr. 2016).
Anyway, I made tmpnb image with Alpine Linux as base, resulting in very small image (79 MB instead of 596 MB). I am testing it now, will write here later.

**Comment by misolietavec** [comment]
**Correction**: it is up-to date, but the python:3.4-wheezy image is a complete mess. In this image, all python2.7 packages are installed, besides this, complete development including gcc, g++, many *-dev packages, (more than 84) also for Xwindow, etc.  Python 3.4 is installed by compilation, not by means of distribution, with the /usr/local prefix and is forced by PATH=/usr/loca/lbin: ... In Debian wheezy there was no Python3, from that are all the unnecessary complications. This image should be replaced by something more appropriate, e.g. 3.5-slim (200 MB) or 3.5-alpine (89 MB). All that images have compiled python, in /usr/local (this is good for separation of distribution-installed (apt, apk) and pip-installed packages) .

**Comment by willingc** [comment]
Thanks @misolietavec. I think your suggestion for 3.5-slim is a good one. :sunny:

**Comment by rgbkrk** [comment]
Feel free to make a PR with the alpine based image @misolietavec.

**Comment by misolietavec** [comment]
I made PR, @willingc merged it, issue can be closed.
