### ISSUE TITLE
How to customize message "Starting a new notebook server just for you"?

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/tmpnb#279]
Is it possible to customize the message that is seen when you start a new notebook?

"Starting a new notebook server just for you"

We were hoping to brand this page a little for our own organization.

**Comment by willingc** [comment]
@rwmajor2 You may edit the template that contains the phrase and then use the edited template in your own tmpnb deployment: https://github.com/jupyter/tmpnb/blob/master/templates/loading.html#L22
