### ISSUE TITLE
Provide visual view of stats

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/tmpnb#95]
This is a dupe of https://github.com/jupyter/tmpnb-redirector/issues/1, but likely belongs in both tmpnb and tmpnb-redirector since they're using the same "spec".

I'm kind of wishing we had a beautiful front-end stats page (which could just be at stats.example.org), or we could make two endpoints on a given tmpnb server `/stats` for a beautiful mockup of the data and `/api/stats` for the raw JSON.

In addition, some things I've wanted during a deploy:

* List version of the containers that are running
* Some aggregated activity data (e.g. number of `docker logs` of individual containers)

**Comment by rgbkrk** [comment]
We should try to adhere close to the same spec as the binder project for these temporary environments. This one is a bit tricky for operations since currently tmpnb-redirector relies on the `/stats` endpoint for JSON.

We'll just have to do a migration once we conform to an API + endpoints.

**Comment by minrk** [comment]
yeah, keeping JSON under `/api/` seems to be a consistently good idea. A human version of that rendered on `/stats` seems sensible enough.

**Comment by rgbkrk** [comment]
Done in #162
